require("core.config.plugins.lualine")
require("core.config.plugins.bufferline")
require("core.config.plugins.themes")
require("core.config.plugins.comment")
require("core.config.plugins.laravel")
require("core.config.plugins.lsp")
require("core.config.plugins.copliot-chat")
require("core.config.plugins.harpoon")
require("core.config.plugins.telescope")
require("core.config.plugins.gitsigns")
require("core.config.plugins.window")
-- require("core.config.plugins.myterm")
require("core.config.plugins.snippets")
require("core.config.plugins.oil-nvim")
require("core.config.plugins.todo")

-- require("core.config.plugins.neo-tree")
-- require("core.config.plugins.nvim-tree")
require("core.config.plugins.toggle-term")
